matrix:
  include:
    language: java
    jdk: oraclejdk8
    before_install:
      - cd kotlin-back
    after_success:
      - bash <(curl -s https://codecov.io/bash) -s kotlin-back -cF kotlin
notifications:
  email: false