matrix:
  include:
    language: java
    jdk: oraclejdk8
    before_script:
      - cd kotlin-back
      - chmod +x gradlew
    script:
      - ./gradlew check
      - ./gradlew jacocoTestReport
     before_cache:
       - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
       - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
     cache:
       directories:
         - $HOME/.gradle/caches/
         - $HOME/.gradle/wrapper/
    after_success:
     - cd ..
     - pwd
     - bash <(curl -s https://codecov.io/bash) -s kotlin-back/build/reports/jacoco -cF kotlin
  include:
    language: node_js
    before_script:
       - cd vuejs-front
    script:
     - npm i
     - npm test
    cache:
      directories:
        - ".eslintcache"
        - "node_modules"
    after_success:
      - cd ..
      - pwd
      - bash <(curl -s https://codecov.io/bash) -s vuejs-front/test/unit/coverage -cF vuejs
notifications:
  email: false